### PR TITLE
Prepare for JMMServer optimization **Completely backwards compatible**

### PR DESCRIPTION
**Pull request by da3dsoul**

### CODE REVIEW

**Comment by da3dsoul** [comment]
I'm still ironing out a small kink and cleaning up debug stuff on the JMMServer side before I PR it

**Comment by da3dsoul** [comment]
Nice and clean http://pastebin.com/C88tK34g

**Comment by bigretromike** [comment]
jMMServer will be release any time soon, so that PR will be for another version. This also look clean.

**Comment by da3dsoul** [comment]
Unfortunately, this doesn't offer much of a performance increase on local host, but from my phone, it's noticeably faster.

**Comment by bigretromike** [comment]
It dosn't matter. If this wont help on pc, important thing is it help in some cases and don't break anything on other :-)

**Pull request merged**
