### PR TITLE
Create strings.po

### PR DESCRIPTION
**Pull request by Eng2Heb**

### CODE REVIEW

**Comment by da3dsoul** [comment]
Ugh but now I need to properly localize everything

**Comment by da3dsoul** [comment]
And make the strings.po file less stupid

**Comment by bigretromike** [comment]
Hahaha. Don't worry to much. Also thanks for push I will merge it as soon as I check some random strings so we don't offend anyone :-). Glad you liked our work.


On October 30, 2017 10:12:44 AM GMT+01:00, Thomas Baer <notifications@github.com> wrote:
>And make the strings.po file less stupid
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/pull/220#issuecomment-340384930

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
If you are willing, I'll reorganize it and extract all of the strings, then you can localize everything rather than having it be a weird half English

**Comment by Eng2Heb** [comment]
Cool.
Sorry for the trubles.
I'll falow the English strings file.

**Comment by bigretromike** [comment]
Not a big trouble. We could do it so people would push other languages :-) and make the Nakamori experience richer 

On October 30, 2017 10:19:10 AM GMT+01:00, "A. Dambledore" <notifications@github.com> wrote:
>Cool.
>Sorry for the trubles.
>I'll falow the English strings file.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/pull/220#issuecomment-340386593

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
Half English ain't that bad but we can do it now so less work later :-)

On October 30, 2017 10:16:08 AM GMT+01:00, Thomas Baer <notifications@github.com> wrote:
>If you are willing, I'll reorganize it and extract all of the strings,
>then you can localize everything rather than having it be a weird half
>English
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/pull/220#issuecomment-340385842

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
It's the kind of trouble like someone handing you a 50kg bag of money. You aren't going to say no, but now you need to motivate yourself to carry it to the bank

**Comment by bigretromike** [comment]
hahaha - true, true 👍

**Comment by bigretromike** [comment]
@Eng2Heb I would like to ask you: are you using Nakamori ? if so which shoko version you using ?

**Comment by Eng2Heb** [comment]
As far as I can remmember I tested it with server version is 3.704

**Comment by bigretromike** [comment]
So you tested it :-) good hope the menu look good. I done recall, does kodi auto align heb to right ? its supported via OS ?

**Comment by Eng2Heb** [comment]
The align is not to the right (like all  the translated addons) but we can leave with it.
Kodi itself needs to improve it support in rtl languages.

**Comment by Eng2Heb** [comment]
The align is not to the right (like all  the translated addons) but we can leave with it.
Kodi itself needs to improve it support in rtl languages.

**Pull request merged**
